DELIMITER $$

CREATE TRIGGER TRG_VALIDA_LIMITE
BEFORE INSERT ON LIMITE_CONSUMO
FOR EACH ROW
BEGIN
  IF NEW.LIMITE_KWH_DIA <= 0 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'O limite de consumo deve ser maior que zero';
  END IF;
END$$

DELIMITER ;

DELIMITER $$

CREATE TRIGGER TRG_VALIDA_LIMITE_UPD
BEFORE UPDATE ON LIMITE_CONSUMO
FOR EACH ROW
BEGIN
  IF NEW.LIMITE_KWH_DIA <= 0 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'O limite de consumo deve ser maior que zero';
  END IF;
END$$

DELIMITER ;