-- Tabela USUARIOS: armazena informações dos usuários do sistema
CREATE TABLE USUARIOS (
    ID_USUARIO BIGINT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    SENHA VARCHAR(100) NOT NULL,
    ROLE VARCHAR(50) DEFAULT 'USER'
);