-- Tabela USUARIO: armazena informações dos usuários do sistema
CREATE TABLE USUARIOS (
    ID_USUARIO NUMBER PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    SENHA VARCHAR(100) NOT NULL,
    ROLE VARCHAR2(50) DEFAULT 'USER'
); 