-- Tabela LIMITE_CONSUMO: define limites de consumo por área
CREATE TABLE LIMITE_CONSUMO (
    ID_LIMITE BIGINT PRIMARY KEY AUTO_INCREMENT,
    LOCALIZACAO VARCHAR(100) NOT NULL,
    LIMITE_KWH_DIA DECIMAL(10,2) NOT NULL,
    DATA_INICIO DATE NOT NULL,
    DATA_FIM DATE
);