-- Tabela LIMITE_CONSUMO: define limites de consumo por área
CREATE TABLE LIMITE_CONSUMO (
    ID_LIMITE NUMBER PRIMARY KEY,
    LOCALIZACAO VARCHAR2(100) NOT NULL,
    LIMITE_KWH_DIA NUMBER NOT NULL,
    DATA_INICIO DATE NOT NULL,
    DATA_FIM DATE
);