-- Tabela DISPOSITIVO: armazena informações sobre dispositivos consumidores de energia
CREATE TABLE DISPOSITIVO (
    ID_DISPOSITIVO BIGINT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    LOCALIZACAO VARCHAR(100) NOT NULL,
    POTENCIA_WATTS DECIMAL(10,2) NOT NULL,
    STATUS VARCHAR(10) DEFAULT 'ATIVO',
    CHECK (STATUS IN ('ATIVO', 'INATIVO'))
);