-- Tabela DISPOSITIVO: armazena informações sobre dispositivos consumidores de energia
CREATE TABLE DISPOSITIVO (
    ID_DISPOSITIVO NUMBER PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    LOCALIZACAO VARCHAR2(100) NOT NULL,
    POTENCIA_WATTS NUMBER NOT NULL,
    STATUS VARCHAR2(10) DEFAULT 'ATIVO' CHECK (STATUS IN ('ATIVO', 'INATIVO'))
);