-- Tabela SENSOR_IOT: armazena informações dos sensores IoT
CREATE TABLE SENSOR_IOT (
    ID_SENSOR BIGINT PRIMARY KEY AUTO_INCREMENT,
    TIPO_SENSOR VARCHAR(50) NOT NULL,
    DATA_INSTALACAO DATE NOT NULL
);