-- Tabela CONSUMO_ENERGIA: registra o consumo energético por dispositivo
CREATE TABLE CONSUMO_ENERGIA (
    ID_CONSUMO BIGINT PRIMARY KEY AUTO_INCREMENT,
    DATA_HORA DATETIME NOT NULL,
    CONSUMO_KWH DECIMAL(10,2) NOT NULL
);