-- Tabela CONSUMO_ENERGIA: registra o consumo energético por dispositivo
CREATE TABLE CONSUMO_ENERGIA (
    ID_CONSUMO NUMBER PRIMARY KEY,
    DATA_HORA TIMESTAMP NOT NULL,
    CONSUMO_KWH NUMBER NOT NULL
);