-- Tabela ALERTA_ENERGIA: registra alertas gerados por consumo excessivo
CREATE TABLE ALERTA_ENERGIA (
    ID_ALERTA NUMBER PRIMARY KEY,
    MENSAGEM VARCHAR2(500) NOT NULL,
    DATA_ALERTA TIMESTAMP NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'PENDENTE' CHECK (STATUS IN ('PENDENTE', 'RESOLVIDO'))
);