-- Tabela ALERTA_ENERGIA: registra alertas gerados por consumo excessivo
CREATE TABLE ALERTA_ENERGIA (
    ID_ALERTA BIGINT PRIMARY KEY AUTO_INCREMENT,
    MENSAGEM VARCHAR(500) NOT NULL,
    DATA_ALERTA DATETIME NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'PENDENTE',
    CHECK (STATUS IN ('PENDENTE', 'RESOLVIDO'))
);