-- Adiciona chave estrangeira de LIMITE_CONSUMO em DISPOSITIVO
ALTER TABLE DISPOSITIVO
ADD COLUMN ID_LIMITE BIGINT;

ALTER TABLE DISPOSITIVO
ADD CONSTRAINT fk_limiteConsumo_dispositivo
FOREIGN KEY (ID_LIMITE)
REFERENCES LIMITE_CONSUMO(ID_LIMITE);

-- Adiciona chave estrangeira de DISPOSITIVO em SENSOR_IOT
ALTER TABLE SENSOR_IOT
ADD COLUMN ID_DISPOSITIVO BIGINT;

ALTER TABLE SENSOR_IOT
ADD CONSTRAINT fk_dispositivo_sensoriot
FOREIGN KEY (ID_DISPOSITIVO)
REFERENCES DISPOSITIVO(ID_DISPOSITIVO);

-- Adiciona chave estrangeira de DISPOSITIVO em CONSUMO_ENERGIA
ALTER TABLE CONSUMO_ENERGIA
ADD COLUMN ID_DISPOSITIVO BIGINT;

ALTER TABLE CONSUMO_ENERGIA
ADD CONSTRAINT fk_dispositivo_consumoenergia
FOREIGN KEY (ID_DISPOSITIVO)
REFERENCES DISPOSITIVO(ID_DISPOSITIVO);

-- Adiciona chave estrangeira de CONSUMO_ENERGIA em ALERTA_ENERGIA
ALTER TABLE ALERTA_ENERGIA
ADD COLUMN ID_CONSUMO BIGINT;

ALTER TABLE ALERTA_ENERGIA
ADD CONSTRAINT fk_consumoenergia_alertaenergia
FOREIGN KEY (ID_CONSUMO)
REFERENCES CONSUMO_ENERGIA(ID_CONSUMO);