-- Sequências para geração de IDs
CREATE SEQUENCE SEQ_DISPOSITIVO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SENSOR START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CONSUMO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_LIMITE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ALERTA START WITH 1 INCREMENT BY 1;