ALTER TABLE DISPOSITIVO
ADD ID_LIMITE NUMBER;

ALTER TABLE DISPOSITIVO
ADD CONSTRAINT fk_limiteConsumo_dispositivo
FOREIGN KEY (ID_LIMITE) 
REFERENCES LIMITE_CONSUMO(ID_LIMITE);

ALTER TABLE SENSOR_IOT
ADD ID_DISPOSITIVO NUMBER;

ALTER TABLE SENSOR_IOT
ADD CONSTRAINT fk_dispositivo_sensoriot
FOREIGN KEY (ID_DISPOSITIVO) 
REFERENCES DISPOSITIVO(ID_DISPOSITIVO);

ALTER TABLE CONSUMO_ENERGIA
ADD ID_DISPOSITIVO NUMBER;

ALTER TABLE CONSUMO_ENERGIA
ADD CONSTRAINT fk_dispositivo_consumoenergia
FOREIGN KEY (ID_DISPOSITIVO) 
REFERENCES DISPOSITIVO(ID_DISPOSITIVO);

ALTER TABLE ALERTA_ENERGIA
ADD ID_CONSUMO NUMBER;

ALTER TABLE ALERTA_ENERGIA
ADD CONSTRAINT fk_consumoenergia_alertaenergia
FOREIGN KEY (ID_CONSUMO) 
REFERENCES CONSUMO_ENERGIA(ID_CONSUMO);
